### ISSUE TITLE
Cannot Connect Ledger Hardware Wallet

### ISSUE THREAD

**Issue by Kernster** [fetchai/asi-alliance-wallet#393]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

When I Click on "Import existing wallet" and "Connect hardware wallet" and connect my existing Ledger hardware wallet, the wallet should be added and the account balance should be shown.[](url)

### Observed Behavior

Instead, I get the error message: "Key ring is not loaded or not empty"

### To Reproduce

Click on "Import existing wallet" and "Connect hardware wallet" and connect an existing Ledger hardware wallet

### Version

0.18.1

### Environment Details (Optional)

```markdown
Ledger Nano S, OS-Version 2.1.0
```

**Comment by Clarevero1** [comment]
> ### Prerequisites
> * [x]  I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
> * [x]  I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports
> 
> ### Category
> Bug (unexpected behavior)
> 
> ### Expected Behavior
> When I Click on "Import existing wallet" and "Connect hardware wallet" and connect my existing Ledger hardware wallet, the wallet should be added and the account balance should be shown.
> 
> ### Observed Behavior
> Instead, I get the error message: "Key ring is not loaded or not empty"
> 
> ### To Reproduce
> Click on "Import existing wallet" and "Connect hardware wallet" and connect an existing Ledger hardware wallet
> 
> ### Version
> 0.18.1
> 
> ### Environment Details (Optional)
> ```
> Ledger Nano S, OS-Version 2.1.0
> ```
> 
> ### Failure Logs (Optional)
> _No response_
> 
> ### Additional Information (Optional)
> _No response_


@Kernster Thank you for opening this issue this could be a hardware failure  It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledger live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by abhifetch** [comment]
Hi @Kernster,

Thanks for raising the issue. We will get back to you with solution for this.

**Comment by summerly01** [comment]
> ### Prerequisites
> * [x]  I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
> * [x]  I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports
> 
> ### Category
> Bug (unexpected behavior)
> 
> ### Expected Behavior
> When I Click on "Import existing wallet" and "Connect hardware wallet" and connect my existing Ledger hardware wallet, the wallet should be added and the account balance should be shown.
> 
> ### Observed Behavior
> Instead, I get the error message: "Key ring is not loaded or not empty"
> 
> ### To Reproduce
> Click on "Import existing wallet" and "Connect hardware wallet" and connect an existing Ledger hardware wallet
> 
> ### Version
> 0.18.1
> 
> ### Environment Details (Optional)
> ```
> Ledger Nano S, OS-Version 2.1.0
> ```
> 
> ### Failure Logs (Optional)
> _No response_
> 
> ### Additional Information (Optional)
> _No response_

This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@abhifetch

**Comment by abhifetch** [comment]
Hi @Kernster,

Can you please confirm if this is working for you now?
