### ISSUE TITLE
ASI Wallet Native Bridge receiving half of sent tokens.

### ISSUE THREAD

**Issue by rw2203** [fetchai/asi-alliance-wallet#421]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Observed Behavior

I attempted to use the native bridge of the ASI wallet to send Fetch tokens to another wallet on the ERC20 chain.  Only half of the sent tokens arrived in the other wallet.  Mintscan says the transaction was a success.

### Version

0.19.2

**Comment by consensys-mod** [comment]
> ### Prerequisites
> * [x]  I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
> * [x]  I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports
> 
> ### Category
> Bug (unexpected behavior)
> 
> ### Expected Behavior
> _No response_
> 
> ### Observed Behavior
> I attempted to use the native bridge of the ASI wallet to send Fetch tokens to another wallet on the ERC20 chain. Only half of the sent tokens arrived in the other wallet. Mintscan says the transaction was a success.
> 
> ### To Reproduce
> _No response_
> 
> ### Version
> 0.19.2
> 
> ### Environment Details (Optional)
> _No response_
> 
> ### Failure Logs (Optional)
> _No response_
> 
> ### Additional Information (Optional)
> _No response_

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [ASI Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Vickynicole** [comment]
Hello @rw2203 
If Mintscan says the transaction was a success but only half of the tokens arrived, it could be an issue with the bridge itself. Have you checked if there are any fees or specific conditions that might have caused only part of the tokens to transfer?

**Comment by rw2203** [comment]
> Hello @rw2203 If Mintscan says the transaction was a success but only half of the tokens arrived, it could be an issue with the bridge itself. Have you checked if there are any fees or specific conditions that might have caused only part of the tokens to transfer?

Apparently there is a 50 fetch fee to use the native to ERC20 bridge that I was unaware of and is not displayed in the wallet, but is shown on the old token bridge website. (I transferred 100 fetch as a test)

Thanks for your help.

**Comment by Vickynicole** [comment]
@rw2203 has it been resolved now ?

**Comment by rw2203** [comment]
Resolved in the sense that I know what happened.  I won't get that 50 fetch back thought.  C'est la vie.

**Comment by Vickynicole** [comment]
@rw2203 At least you know what happened,and you can get it back

**Comment by rw2203** [comment]
I'm closing this thread, I figured out what happened.  Would be nice if the native bridge on the ASI wallet made the fee as apparent as it is on the token bridge website.

**Comment by Vickynicole** [comment]
@rw2203 or you can just talk to the support about it I can refer you to the support team

**Comment by rw2203** [comment]
Would support do anything about it if it's a legitimate fee though?

**Comment by Vickynicole** [comment]
@rw2203 they should be able to figure something out

**Comment by rw2203** [comment]
Don't worry about it.  Thanks for the help!

**Comment by Vickynicole** [comment]
@rw2203 
 the official support live chat with the ticket ID FET07638
Please see the link below to our dedicated support line:
[Fetch Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Vickynicole** [comment]
> Don't worry about it. Thanks for the help!

Okay
