### ISSUE TITLE
The ASLI alliance Wallet extension is not working.

### ISSUE THREAD

**Issue by Farid110777** [fetchai/asi-alliance-wallet#428]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

Reward claim, seed display, Link ASI mobile work

### Observed Behavior

Reward withdrawal, Neither the seed display nor the Link ASI mobile work.

### To Reproduce

Try to do the three things above.

### Version

0.19.03

### Additional Information (Optional)

```markdown
chrome 131.6778.205
```

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [ASI SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by mikel879881** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
